config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/healthcast_quiz_home'
  get 'welcome/healthcast_quiz_morley_robbins'
  root 'welcome#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merit/badge_rules.rb
# Be sure to restart your server when you modify this file.
#
# +grant_on+ accepts:
# * Nothing (always grants)
# * A block which evaluates to boolean (recieves the object as parameter)
# * A block with a hash composed of methods to run on the target object with
#   expected values (+votes: 5+ for instance).
#
# +grant_on+ can have a +:to+ method name, which called over the target object
# should retrieve the object to badge (could be +:user+, +:self+, +:follower+,
# etc). If it's not defined merit will apply the badge to the user who
# triggered the action (:action_user by default). If it's :itself, it badges
# the created object (new user for instance).
#
# The :temporary option indicates that if the condition doesn't hold but the
# badge is granted, then it's removed. It's false by default (badges are kept
# forever).

module Merit
  class BadgeRules
    include Merit::BadgeRulesMethods

    def initialize
      # If it creates user, grant badge
      # Should be "current_user" after registration for badge to be granted.
      # Find badge by badge_id, badge_id takes presidence over badge
      # grant_on 'users#create', badge_id: 7, badge: 'just-registered', to: :itself

      # If it has 10 comments, grant commenter-10 badge
      # grant_on 'comments#create', badge: 'commenter', level: 10 do |comment|
      #   comment.user.comments.count == 10
      # end

      # If it has 5 votes, grant relevant-commenter badge
      # grant_on 'comments#vote', badge: 'relevant-commenter',
      #   to: :user do |comment|
      #
      #   comment.votes.count == 5
      # end

      # Changes his name by one wider than 4 chars (arbitrary ruby code case)
      # grant_on 'registrations#update', badge: 'autobiographer',
      #   temporary: true, model_name: 'User' do |user|
      #
      #   user.name.length > 4
      # end
    end
  end
end

app/models/merit/point_rules.rb
# Be sure to restart your server when you modify this file.
#
# Points are a simple integer value which are given to "meritable" resources
# according to rules in +app/models/merit/point_rules.rb+. They are given on
# actions-triggered, either to the action user or to the method (or array of
# methods) defined in the +:to+ option.
#
# 'score' method may accept a block which evaluates to boolean
# (recieves the object as parameter)

module Merit
  class PointRules
    include Merit::PointRulesMethods

    def initialize
      # score 10, :on => 'users#create' do |user|
      #   user.bio.present?
      # end
      #
      # score 15, :on => 'reviews#create', :to => [:reviewer, :reviewed]
      #
      # score 20, :on => [
      #   'comments#create',
      #   'photos#create'
      # ]
      #
      # score -10, :on => 'comments#destroy'
    end
  end
end

app/models/merit/rank_rules.rb
# Be sure to restart your server when you modify this file.
#
# 5 stars is a common ranking use case. They are not given at specified
# actions like badges, you should define a cron job to test if ranks are to be
# granted.
#
# +set_rank+ accepts:
# * :+level+ ranking level (greater is better)
# * :+to+ model or scope to check if new rankings apply
# * :+level_name+ attribute name (default is empty and results in 'level'
#   attribute, if set it's appended like 'level_#{level_name}')

module Merit
  class RankRules
    include Merit::RankRulesMethods

    def initialize
      # set_rank :level => 1, :to => Commiter.active do |commiter|
      #   commiter.repositories.count > 1 && commiter.followers >= 10
      # end
      #
      # set_rank :level => 2, :to => Commiter.active do |commiter|
      #   commiter.branches.count > 1 && commiter.followers >= 10
      # end
      #
      # set_rank :level => 3, :to => Commiter.active do |commiter|
      #   commiter.branches.count > 2 && commiter.followers >= 20
      # end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_merit

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	#before_action :authenticate_user! // commented out to test nav_guest and nav_user dynamic nav bars
  	protect_from_forgery with: :exception

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">PodcastMash</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <div class="nav-link"><%= link_to "About", welcome_about_path %></div>
      </li>
      <li class="nav-item">
        <div class="nav-link"><%= link_to "Sign up", new_user_registration_path %></div>
      </li>
      <li class="nav-item">
        <div class="nav-link"><%= link_to "Sign in", new_user_session_path %></div>
      </li>            
    </ul>
  </div>
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <span class="navbar-brand"><%= link_to "PodcastMash", welcome_index_path %></span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <div class="nav-link"><%= link_to "Home", welcome_index_path %></div>
      </li>
      <li class="nav-item">
        <div class="nav-link"><%= link_to "About", welcome_about_path %></div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Account</a>
          <span class="dropdown-item"><%= link_to "Settings", edit_user_registration_path %></span>
          <div class="dropdown-divider"></div>
          <span class="dropdown-item"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></span>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PodcastMashApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render '/welcome/nav' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/_nav.html.erb
<!--- render nav_guest if not a user or not signed in, render nab_user if a user and signed in -->

<% if !user_signed_in? %>
  <%= render '/layouts/nav_guest' %>
<% else %>
  <%= render '/layouts/nav_user' %>
<% end %>

app/views/welcome/about.html.erb
<div class="container">
	<div class="page-container">
		<h1>About <span style="font-family: 'Chicle', cursive;">PodcastMash<span></h1>
		<p><strong>A mash-up of Health-oriented Podcasts and Trivia.</strong> Health Podcasts are an important source of personal health information. This website serves the health of individuals by testing each person on their knowledge of the podcast content; helping important information stay top-of-mind and useable as we each face life's challenges.</p>
		<p>Have fun, get healthy, stay healthy, and learn!</p>
	</div>
</div>

app/views/welcome/healthcast_quiz_home.html.erb
<div class="container">
	<div class="quiz-home">
		<div class="quiz-row hc-now-quiz-2">
			<h5><%= link_to "HealthCast Now: Morley Robbins", welcome_healthcast_quiz_morley_robbins_path %></h5>
			<p>Magnesium Deficiency and Chronic Health Challenges</p>
		</div>
		<div class="quiz-row hc-now-quiz-3">
			<h5>HealthCast Now: Matt Maruca</h5>
			<p>Circadian Biohacking for Optimal Health & Wellness</p>
		</div>
		<div class="quiz-row hc-now-quiz-4">
			<h5>HealthCast Now: Lisa Perkins</h5>
			<p>Hormone Health & Weight Loss for Women and Men</p>
		</div>		
		<div class="quiz-row hc-now-quiz-1">
			<h5>HealthCast Now: Dr. Lindsay Henderson</h5>
			<p>Sleep, Wellness and Optimal Health for Children and Toddlers</p>
		</div>
	</div>
</div>

app/views/welcome/healthcast_quiz_morley_robbins.html.erb
<!DOCTYPE <html>
<head>
	<title>Morley Robbins Quiz</title>
</head>
<body>
	<div class="quiz-header">
	<h4>HealthCast Now: Morley Robbins</h4>
	<p>Magnesium Deficiency and Chronic Health Challenges</p>
	</div>
	<div class="container">
		<div class="quiz-container">
			<div class="box a">1</div>
			<div class="box b">2</div>
			<div class="box c">3</div>
			<div class="box d">4</div>
			<div class="box e">5</div>
			<div class="box f">6</div>
			<div class="box g">7</div>
			<div class="box h">8</div>
			<div class="box i">9</div>
			<div class="box j">10</div>
			<div class="box k">11</div>
			<div class="box l">12</div>
			<div class="box m">13</div>
			<div class="box n">14</div>
			<div class="box o">15</div>
			<div class="box p">16</div>
			<div class="box q">17</div>
			<div class="box r">18</div>
			<div class="box s">19</div>
			<div class="box t">20</div>						
		</div>
	</div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
	<div class="page-container">
		<div class="grid">

			<div class="card podcast" style="width: 12rem;">
			  <img class="card-img-top" src="https://res.cloudinary.com/deallen7/image/upload/v1522191279/bengreenfield.jpg" alt="Card image cap">
			  <div class="card-body">
			    <h6 class="card-title">Ben Greenfield</h6>
			    <p class="card-text">Ben Greenfield is a personal trainer, holistic nutritionish and health expert.</p>
			    <a href="#" class="quiz-link">Quiz List</a>
			  </div>
			</div>
	
			<div class="card podcast" style="width: 12rem;">
			  <img class="card-img-top" src="https://res.cloudinary.com/deallen7/image/upload/v1522193101/bulletproof-radio.jpg" alt="Card image cap">
			  <div class="card-body">
			    <h6 class="card-title">Bulletproof Radio</h6>
			    <p class="card-text">Biohacking, cognitive enhacement, diet and much more.</p>
			    <a href="#" class="quiz-link">Quiz List</a>
			  </div>
			</div>

			<div class="card podcast" style="width: 12rem;">
			  <img class="card-img-top" src="https://res.cloudinary.com/deallen7/image/upload/v1522193317/healhcast-now.jpg" alt="Card image cap">
			  <div class="card-body">
			    <h6 class="card-title">Healthcast Now</h6>
			    
			    <p class="card-text">All about Health, Wellness and Circadian Optimization.</p>
			    <span class="quiz-link"><%= link_to "Quiz List", welcome_healthcast_quiz_home_path %></span>
			  </div>
			</div>	

			<div class="card podcast" style="width: 12rem;">
			  <img class="card-img-top" src="https://res.cloudinary.com/deallen7/image/upload/v1522193170/paleo-solution.jpg" alt="Card image cap">
			  <div class="card-body">
			    <h6 class="card-title">The Paleo Solution</h6>
			    <p class="card-text">Spanning the connected topics of performance, health and longevity</p>
			    <a href="#" class="quiz-link">Quiz List</a>
			  </div>
			</div>

			<div class="card podcast" style="width: 12rem;">
			  <img class="card-img-top" src="https://res.cloudinary.com/deallen7/image/upload/v1522193320/found-my-fitness.jpg" alt="Card image cap">
			  <div class="card-body">
			    <h6 class="card-title">Found My Fitness</h6>
			    <p class="card-text">Increase healthspan, well-being, and performance.</p>
			    <a href="#" class="quiz-link">Quiz List</a>
			  </div>
			</div>

		</div>
	</div>
</div>